spring:
  messages:
    basename: i18n.messages
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
jwt:
  header: Authorization
  secret: secret

logging:
  file:
    name: log-file.log
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true


